config/routes.rb
Rails.application.routes.draw do
  resources :advogados
  root 'advogados#index'

  devise_for :users
  resources :processos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advogado.rb
class Advogado < ApplicationRecord
  has_many :processos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/processo.rb
class Processo < ApplicationRecord
  has_and_belongs_to_many :advogados

  def self.search (query)
    where("num_processo like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/advogados_controller.rb
class AdvogadosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_advogado, only: [:show, :edit, :update, :destroy]

  # GET /advogados
  # GET /advogados.json
  def index
    @advogados = Advogado.all
  end

  # GET /advogados/1
  # GET /advogados/1.json
  def show
  end

  # GET /advogados/new
  def new
    @advogado = Advogado.new
  end

  # GET /advogados/1/edit
  def edit
  end

  # POST /advogados
  # POST /advogados.json
  def create
    @advogado = Advogado.new(advogado_params)

    respond_to do |format|
      if @advogado.save
        format.html { redirect_to @advogado, notice: 'Advogado was successfully created.' }
        format.json { render :show, status: :created, location: @advogado }
      else
        format.html { render :new }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advogados/1
  # PATCH/PUT /advogados/1.json
  def update
    respond_to do |format|
      if @advogado.update(advogado_params)
        format.html { redirect_to @advogado, notice: 'Advogado was successfully updated.' }
        format.json { render :show, status: :ok, location: @advogado }
      else
        format.html { render :edit }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advogados/1
  # DELETE /advogados/1.json
  def destroy
    @advogado.destroy
    respond_to do |format|
      format.html { redirect_to advogados_url, notice: 'Advogado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advogado
      @advogado = Advogado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advogado_params
      params.require(:advogado).permit(:nome, :email, :n_OAB)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_processo, only: [:show, :edit, :update, :destroy]

  # GET /processos
  # GET /processos.json
  def index
    if params[:search]
      @processos = Processo.all.search(params[:search])
    else
      @processos = Processo.all
    end
  end

  # GET /processos/1
  # GET /processos/1.json
  def show
  end

  # GET /processos/new
  def new
    @processo = Processo.new
  end

  # GET /processos/1/edit
  def edit
  end

  # POST /processos
  # POST /processos.json
  def create
    @processo = Processo.new(processo_params)

    respond_to do |format|
      if @processo.save
        format.html { redirect_to @processo, notice: 'Processo was successfully created.' }
        format.json { render :show, status: :created, location: @processo }
      else
        format.html { render :new }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processos/1
  # PATCH/PUT /processos/1.json
  def update
    respond_to do |format|
      if @processo.update(processo_params)
        format.html { redirect_to @processo, notice: 'Processo was successfully updated.' }
        format.json { render :show, status: :ok, location: @processo }
      else
        format.html { render :edit }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processos/1
  # DELETE /processos/1.json
  def destroy
    @processo.destroy
    respond_to do |format|
      format.html { redirect_to processos_url, notice: 'Processo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processo
      @processo = Processo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processo_params
      params.require(:processo).permit(:cliente, :ex_adversa, :natureza, :assunto, :tipo_acao, :juizo, :num_processo, :ultima_movimentacao, :ultimo_contato_cliente, :contato_agendado, :adv_principal, :adv_assistente)
    end
end

app/helpers/advogados_helper.rb
module AdvogadosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/views/advogados/_form.html.erb
<%= form_with(model: advogado, local: true) do |form| %>
  <% if advogado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advogado.errors.count, "error") %> prohibited this advogado from being saved:</h2>

      <ul>
      <% advogado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :advogado_nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :advogado_email %>
  </div>

  <div class="field">
    <%= form.label :n_OAB %>
    <%= form.text_field :n_OAB, id: :advogado_n_OAB %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advogados/edit.html.erb
<h1>Editing Advogado</h1>

<%= render 'form', advogado: @advogado %>

<%= link_to 'Show', @advogado %> |
<%= link_to 'Back', advogados_path %>

app/views/advogados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advogados</h1>
<%=link_to 'Sair',destroy_user_session_path, method: :delete %>
<%=link_to 'Processos',processos_path %>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>N oab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advogados.each do |advogado| %>
      <tr>
        <td><%= advogado.nome %></td>
        <td><%= advogado.email %></td>
        <td><%= advogado.n_OAB %></td>
        <td><%= link_to 'Show', advogado %></td>
        <td><%= link_to 'Edit', edit_advogado_path(advogado) %></td>
        <td><%= link_to 'Destroy', advogado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advogado', new_advogado_path %>

app/views/advogados/new.html.erb
<h1>New Advogado</h1>

<%= render 'form', advogado: @advogado %>

<%= link_to 'Back', advogados_path %>

app/views/advogados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @advogado.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advogado.email %>
</p>

<p>
  <strong>N oab:</strong>
  <%= @advogado.n_OAB %>
</p>

<%= link_to 'Edit', edit_advogado_path(@advogado) %> |
<%= link_to 'Back', advogados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorDeProcessos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/processos/_form.html.erb
<%= form_with(model: processo, local: true) do |form| %>
  <% if processo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(processo.errors.count, "error") %> prohibited this processo from being saved:</h2>

      <ul>
      <% processo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.text_field :cliente, id: :processo_cliente %>
  </div>

  <div class="field">
    <%= form.label :ex_adversa %>
    <%= form.text_field :ex_adversa, id: :processo_ex_adversa %>
  </div>

  <div class="field">
    <%= form.label :natureza %>
    <%= form.text_field :natureza, id: :processo_natureza %>
  </div>

  <div class="field">
    <%= form.label :assunto %>
    <%= form.text_field :assunto, id: :processo_assunto %>
  </div>

  <div class="field">
    <%= form.label :tipo_acao %>
    <%= form.text_field :tipo_acao, id: :processo_tipo_acao %>
  </div>

  <div class="field">
    <%= form.label :juizo %>
    <%= form.text_field :juizo, id: :processo_juizo %>
  </div>

  <div class="field">
    <%= form.label :num_processo %>
    <%= form.text_field :num_processo, id: :processo_num_processo %>
  </div>

  <div class="field">
    <%= form.label :ultima_movimentacao %>
    <%= form.text_field :ultima_movimentacao, id: :processo_ultima_movimentacao %>
  </div>

  <div class="field">
    <%= form.label :ultimo_contato_cliente %>
    <%= form.date_select :ultimo_contato_cliente, id: :processo_ultimo_contato_cliente %>
  </div>

  <div class="field">
    <%= form.label :contato_agendado %>
    <%= form.date_select :contato_agendado, id: :processo_contato_agendado %>
  </div>

  <div class="field">
    <%= form.label :adv_principal %>
    <%= form.text_field :adv_principal, id: :processo_adv_principal %>
  </div>

  <div class="field">
    <%= form.label :adv_assistente %>
    <%= form.text_field :adv_assistente, id: :processo_adv_assistente %>
  </div>

  <div class="actions">
    <%= form.submit value='submit'%>
  </div>
<% end %>

app/views/processos/edit.html.erb
<h1>Editing Processo</h1>

<%= render 'form', processo: @processo %>

<%= link_to 'Show', @processo %> |
<%= link_to 'Back', processos_path %>

app/views/processos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Processos</h1>
<hr>
<%= form_tag(processos_path, :method => :get) do %>
  <%=text_field_tag 'search', nil, placeholder: 'Nº do processo' %>
  <%=submit_tag "Buscar" %>
<%end %>

<%= link_to "Voltar", advogados_path %>
<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Numero do processo</th>
    </tr>
  </thead>

  <tbody>
    <% @processos.each do |processo| %>
      <tr>
        <td><%= processo.cliente %></td>
        <td><%= processo.num_processo %></td>
        <td><%= link_to 'Show', processo, id: "s-#{processo.num_processo}" %></td>
        <td><%= link_to 'Edit', edit_processo_path(processo), id: "e-#{processo.num_processo}" %></td>
        <td><%= link_to 'Destroy', processo, id: "d-#{processo.num_processo}" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Processo', new_processo_path %>

app/views/processos/new.html.erb
<h1>New Processo</h1>

<%= render 'form', processo: @processo %>

<%= link_to 'Back', processos_path %>

app/views/processos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Processo - <%= @processo.num_processo %></h1>
<hr>

<p>
  <strong>Cliente:</strong>
  <%= @processo.cliente %>
</p>

<p>
  <strong>Ex adversa:</strong>
  <%= @processo.ex_adversa %>
</p>

<p>
  <strong>Natureza:</strong>
  <%= @processo.natureza %>
</p>

<p>
  <strong>Assunto:</strong>
  <%= @processo.assunto %>
</p>

<p>
  <strong>Tipo acao:</strong>
  <%= @processo.tipo_acao %>
</p>

<p>
  <strong>Juizo:</strong>
  <%= @processo.juizo %>
</p>

<p>
  <strong>Num processo:</strong>
  <%= @processo.num_processo %>
</p>

<p>
  <strong>Ultima movimentacao:</strong>
  <%= @processo.ultima_movimentacao %>
</p>

<p>
  <strong>Ultimo contato cliente:</strong>
  <%= @processo.ultimo_contato_cliente %>
</p>

<p>
  <strong>Contato agendado:</strong>
  <%= @processo.contato_agendado %>
</p>

<p>
  <strong>Adv principal:</strong>
  <%= @processo.adv_principal %>
</p>

<p>
  <strong>Adv assistente:</strong>
  <%= @processo.adv_assistente %>
</p>

<%= link_to 'Edit', edit_processo_path(@processo) %> |
<%= link_to 'Back', processos_path %>